import { ANALYTICS_DAILY_FACILITY_REQUIREMENTS, ANALYTICS_DAILY_INSPECTOR_REQUIREMENTS, DASHBOARD_ANALYTICS_ENDPOINT } from "./constants";
import type { HomeDashboardSectionConfig, HomeDashboardVisualConfig } from "./types";

export const HOME_DASHBOARD_VISUALS: HomeDashboardVisualConfig[] = [
  {
    id: "summary-total-damage-submissions",
    title: "Total Damage Submissions",
    description: "Damage workflow submissions, with clear/no-damage kept visible.",
    endpoint: DASHBOARD_ANALYTICS_ENDPOINT,
    requiredFields: ["totals.damageReports", "totals.noDamageReports"],
    dataSource: "dashboard-analytics",
    measures: ["damageReports", "noDamageReports"],
    dimensions: ["organization", "date range"],
    slicers: ["from", "to", "facility", "inspector", "status", "inspection type", "VIN", "report id"],
    adapter: "summary totals selector in src/app/home/page.tsx, backed by analytics-adapters.ts readers",
    component: "MetricCard",
    exportFile: "sections/card-data.csv",
    emptyState: "Show zero or backend coverage warning; do not infer damaged from total reports.",
  },
  {
    id: "summary-damaged-today",
    title: "Damaged Submissions Today",
    description: "Daily damaged submission count from explicit backend damaged fields.",
    endpoint: DASHBOARD_ANALYTICS_ENDPOINT,
    requiredFields: ["totals.damageReportsToday or currentPeriod.damageToday"],
    dataSource: "dashboard-analytics",
    measures: ["damageReportsToday", "clearReportsToday"],
    dimensions: ["date"],
    slicers: ["from", "to", "facility", "inspector", "status", "inspection type"],
    adapter: "summary currentPeriod selector in src/app/home/page.tsx",
    component: "MetricCard",
    exportFile: "sections/card-data.csv",
    emptyState: "Show explicit zero when the backend sends no today value.",
  },
  {
    id: "summary-damage-vs-clear",
    title: "Damage vs Clear",
    description: "Side-by-side split when backend sends damaged and clear fields.",
    endpoint: DASHBOARD_ANALYTICS_ENDPOINT,
    requiredFields: ["totals.damageReports", "totals.noDamageReports or totals.clearReports"],
    dataSource: "dashboard-analytics",
    measures: ["damageReports", "noDamageReports"],
    dimensions: ["organization", "date range"],
    slicers: ["from", "to", "facility", "inspector", "status", "inspection type"],
    adapter: "readAnalyticsSplitPair for row-level splits; summary totals selector for headline split",
    component: "DamageClearMetricValue inside MetricCard",
    exportFile: "sections/card-data.csv",
    emptyState: "Show backend coverage warning when split fields are missing.",
  },
  {
    id: "facility-daily-trend",
    title: "Facility Daily Trend",
    description: "Per-day facility clear and damaged breakdown.",
    endpoint: DASHBOARD_ANALYTICS_ENDPOINT,
    requiredFields: ANALYTICS_DAILY_FACILITY_REQUIREMENTS,
    dataSource: "dashboard-analytics",
    measures: ["damageReports", "noDamageReports"],
    dimensions: ["date", "facility label", "facility id"],
    slicers: ["from", "to", "facility", "status", "inspection type"],
    adapter: "buildDailyAnalyticsTrend and buildDashboardDailySplitCoverage",
    component: "Recharts BarChart with DashboardTrendTooltip",
    exportFile: "daily-damage-submission-analytics.csv",
    emptyState: "Show coverage warning if daily rows do not include explicit split fields.",
  },
  {
    id: "inspector-daily-trend",
    title: "Inspector Daily Trend",
    description: "Per-day inspector clear and damaged breakdown.",
    endpoint: DASHBOARD_ANALYTICS_ENDPOINT,
    requiredFields: ANALYTICS_DAILY_INSPECTOR_REQUIREMENTS,
    dataSource: "dashboard-analytics",
    measures: ["damageReports", "noDamageReports", "reportCount"],
    dimensions: ["date", "inspector email", "inspector label"],
    slicers: ["from", "to", "inspector", "facility", "status", "inspection type"],
    adapter: "buildDailyInspectorTrend and buildAnalyticsInspectorSummaries",
    component: "Recharts BarChart with DashboardTrendTooltip",
    exportFile: "daily-inspector-damage-submissions.csv",
    emptyState: "Show coverage warning if inspector rows do not include explicit split fields.",
  },
  {
    id: "severity",
    title: "Severity",
    description: "Damage severity distribution.",
    endpoint: DASHBOARD_ANALYTICS_ENDPOINT,
    requiredFields: ["severity.level", "severity.count"],
    dataSource: "dashboard-analytics",
    measures: ["count"],
    dimensions: ["severity level", "severity label"],
    slicers: ["from", "to", "facility", "inspector", "status", "inspection type", "severity"],
    adapter: "normalizeDashboardSeverityItems and buildSelectedSeverityPieData",
    component: "Recharts PieChart plus ChartFooterTable",
    exportFile: "severity-damage-submission-detail.csv",
    emptyState: "Show empty severity state when no severity rows are returned.",
  },
  {
    id: "top-damage-areas",
    title: "Top Damage Areas",
    description: "Highest-volume damaged vehicle areas.",
    endpoint: DASHBOARD_ANALYTICS_ENDPOINT,
    requiredFields: ["topAreas.name", "topAreas.count"],
    dataSource: "dashboard-analytics",
    measures: ["count"],
    dimensions: ["damage area"],
    slicers: ["from", "to", "facility", "inspector", "status", "inspection type", "damage area"],
    adapter: "normalizeAnalyticsTopBuckets and buildAreaPieData",
    component: "Recharts PieChart plus ChartFooterTable",
    exportFile: "damage-area-submission-detail.csv",
    emptyState: "Show empty top-area state when backend sends no rows.",
  },
  {
    id: "top-damage-types",
    title: "Top Damage Types",
    description: "Highest-volume damage type labels.",
    endpoint: DASHBOARD_ANALYTICS_ENDPOINT,
    requiredFields: ["topTypes.name", "topTypes.count"],
    dataSource: "dashboard-analytics",
    measures: ["count"],
    dimensions: ["damage type"],
    slicers: ["from", "to", "facility", "inspector", "status", "inspection type"],
    adapter: "normalizeAnalyticsTopBuckets",
    component: "HorizontalBarList or chart card",
    exportFile: "top-damage-types.csv",
    emptyState: "Show empty top-type state when backend sends no rows.",
  },
];

export const HOME_DASHBOARD_SECTIONS: HomeDashboardSectionConfig[] = [
  {
    id: "scoreboard",
    title: "Scoreboard",
    description: "Top-level measures that answer how many submissions exist and how they split.",
    visualIds: [
      "summary-total-damage-submissions",
      "summary-damaged-today",
      "summary-damage-vs-clear",
    ],
  },
  {
    id: "daily-trends",
    title: "Daily Trends",
    description: "Time-series visuals scoped by the same URL-driven slicers.",
    visualIds: ["facility-daily-trend", "inspector-daily-trend"],
  },
  {
    id: "damage-profile",
    title: "Damage Profile",
    description: "Severity, damage area, and damage type visuals that explain where the volume is coming from.",
    visualIds: ["severity", "top-damage-areas", "top-damage-types"],
  },
];

export function getHomeDashboardVisual(id: HomeDashboardVisualConfig["id"]): HomeDashboardVisualConfig {
  return HOME_DASHBOARD_VISUALS.find((visual) => visual.id === id) ?? HOME_DASHBOARD_VISUALS[0];
}

export function getHomeDashboardSectionVisuals(sectionId: string): HomeDashboardVisualConfig[] {
  const section = HOME_DASHBOARD_SECTIONS.find((item) => item.id === sectionId);
  if (!section) return [];
  return section.visualIds.map(getHomeDashboardVisual);
}
