import type { DashboardWidgetConfig } from "./dashboardTypes";
import {
  selectDamageAreaRows,
  selectDailyDamageTrendRows,
  selectDamagedToday,
  selectInspectorVolumeRows,
  selectRsaReports,
  selectSeverityRows,
  selectTopFacilityRows,
  selectTopModelRows,
  selectTopYardRows,
  selectTotalDamageSubmissions,
} from "./selectors";

export const homeDashboardRegistry: DashboardWidgetConfig[] = [
  {
    id: "total-damage-submissions",
    title: "Total Damage Submissions",
    type: "metric",
    selector: selectTotalDamageSubmissions,
    size: "sm",
    exportKey: "totalDamageSubmissions",
  },
  {
    id: "damaged-today",
    title: "Damaged Today",
    type: "metric",
    selector: selectDamagedToday,
    size: "sm",
    exportKey: "damagedToday",
  },
  {
    id: "rsa-reports",
    title: "RSA Reports",
    type: "metric",
    selector: selectRsaReports,
    size: "sm",
    exportKey: "rsaReports",
  },
  {
    id: "daily-damage-trend",
    title: "Daily Damage Trend",
    type: "line",
    selector: selectDailyDamageTrendRows,
    size: "wide",
    exportKey: "dailyDamageTrend",
  },
  {
    id: "top-facilities",
    title: "Top Facilities",
    type: "bar",
    selector: selectTopFacilityRows,
    size: "md",
    clickFilter: (datum) => ({ key: "facility", value: datum.filterValue || datum.label }),
    exportKey: "topFacilities",
  },
  {
    id: "top-yards",
    title: "Top Yards",
    type: "bar",
    selector: selectTopYardRows,
    size: "md",
    clickFilter: (datum) => ({ key: "yard", value: datum.filterValue || datum.label }),
    exportKey: "topYards",
    emptyLabel: "No yard series returned.",
  },
  {
    id: "top-models",
    title: "Top Models",
    type: "bar",
    selector: selectTopModelRows,
    size: "md",
    clickFilter: (datum) => ({ key: "model", value: datum.filterValue || datum.label }),
    exportKey: "topModels",
    emptyLabel: "No model filter options returned.",
  },
  {
    id: "inspector-volume",
    title: "Inspector Volume",
    type: "bar",
    selector: selectInspectorVolumeRows,
    size: "md",
    clickFilter: (datum) => ({ key: "inspector_email", value: datum.filterValue || datum.label }),
    exportKey: "inspectorVolume",
  },
  {
    id: "severity-distribution",
    title: "Severity",
    type: "pie",
    selector: selectSeverityRows,
    size: "md",
    clickFilter: (datum) => ({ key: "severity", value: datum.filterValue || datum.label }),
    exportKey: "severity",
  },
  {
    id: "top-damage-areas",
    title: "Top Damage Areas",
    type: "bar",
    selector: selectDamageAreaRows,
    size: "md",
    clickFilter: (datum) => ({ key: "damage_area", value: datum.filterValue || datum.label }),
    exportKey: "topDamageAreas",
  },
];
